# app-go-goof.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: go-goof

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-goof-ksa
  namespace: go-goof

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-goof
  namespace: go-goof
  labels:
    app.kubernetes.io/name: go-goof
    app.kubernetes.io/instance: go-goof-instance
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: go-goof
      app.kubernetes.io/instance: go-goof-instance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-goof
        app.kubernetes.io/instance: go-goof-instance
    spec:
      serviceAccountName: go-goof-ksa
      containers:
        - name: go-goof
          image: us-west1-docker.pkg.dev/snyk-cx-se-demo/demo/go-goof:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux